# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/geniusrabbit"

[social.params]
icon = "brand-github"

[[social]]
identifier = "website"
name = "Opensource SSPserver"
url = "https://sspserver.org"

# [[social]]
# identifier = "twitter"
# name = "Twitter"
# url = "https://twitter.com"

# [social.params]
# icon = "brand-twitter"
